services:
  AppBundle\Client\HttpClient:
    class: AppBundle\Client\HttpClient
  AppBundle\RequestAdapter\UserRequestAdapter:
    class: AppBundle\RequestAdapter\UserRequestAdapter
  AppBundle\RequestAdapter\MovieRequestAdapter:
    class: AppBundle\RequestAdapter\MovieRequestAdapter
  blabla_movie.client.omdb_api:
    class: AppBundle\Client\OmdbAPIClient
    arguments:
      - "@AppBundle\\Client\\HttpClient"
      - "%omdb_api_key%"
